name: spectral_distortions

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - cython
  - numpy=1.24
  - matplotlib
  - astropy=5.2
  - asdf
  - asdf-astropy
  - tqdm
  - "typing_extensions>=4.8"

  - pip:
      - showyourwork
      - classy>3.2
      - flt
      - git+https://github.com/GalOrrery/interpolated-coordinates.git
      - git+https://github.com/nstarman/cosmology-compat-class.git@spectral_distortions_paper_branch
