[tool.black]
line-length = 88


[tool.mypy]
    strict = true
    warn_unreachable = true
    enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]


[tool.repo-review]
ignore = [
    "GH102",
    "GH103",
    "PC160",
    "PP",
    "PY",
    "RTD100"
]


[tool.ruff]
src = ["src"]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN101", "ANN102", "ANN401",
    "B008", "B011",
    "COM812",
    "D105", "D107", "D203", "D213", "D417",
    "E402",
    "FA102",
    "FIX002",
    "N80",
    "N812", "N815", "N816",  # mixedCase
    "TD002", "TD003",
    "TID252",  # Relative imports from parent modules are banned
]

[tool.ruff.lint.per-file-ignores]
"src/scripts/*.py" = ["INP001"]  #  implicit namespace package

[tool.ruff.lint.isort]
known-first-party = ["paths"]
known-local-folder = ["src", "cosmo"]
